#!/bin/sh

xrandr --output eDP --primary --mode 1920x1080 --pos 1932x0 --rotate normal --output HDMI-A-0 --mode 1680x1050 --pos 0x0 --rotate normal --output DP-1-0 --off --output DP-1-1 --off
xrandr --output HDMI-A-0 --scale 1.15
